version: 2
jobs:
  build_push:
    docker:
    - image: cimg/base:stable-20.04
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Login to Docker hub
        command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - run:
        name: Build image
        command: make build
    - run:
        name: Push image
        command: make push

workflows:
  version: 2
  build_push:
    jobs:
    - build_push:
        filters:
          branches:
            only:
            - master
